### ISSUE TITLE
Extend API to allow the addition of attributes to unclosed-but-created spans

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [c-cube/ocaml-trace#10]
At the moment, the `~data` API requires all attributes to be known at span-creation time. This isn't always possible.

Consider the case of an HTTP request, on the client-side — when the span is opened, one _cannot_ know the response-code of that request; but before the span is entirely closed, you'd want to attach that information to the span.

Something like `Trace.add_data ~data span_id`, perhaps?

**Comment by c-cube** [comment]
Yes indeed, that's a very reasonable feature. :+1:
