### ISSUE TITLE
duplicate module definition when running dune utop 

### ISSUE THREAD

**Issue by joprice** [c-cube/ocaml-trace#2]
I get an error when trying to start utop via dune, where both the toplevel and this library provide a module named "Trace":

```
Error: Files /nix/store/sqkjv5i2qdwlf2244ifs9ga50m011p05-ocaml5.1.0-beta1-trace-n-a/lib/ocaml/5.1.0~beta1/site-lib/trace/trace.cma(Trace)

       and /nix/store/46vkfb33m24jjl2rj40cd3qfgg8d3inq-ocaml+flambda-5.1.0-beta1/lib/ocaml/compiler-libs/ocamltoplevel.cma(Trace)

       both define a module named Trace```

**Comment by c-cube** [comment]
Yes, that's why there is `trace.core`. I met a similar issue. The compiler library defines `Trace` already so we have to be more explicit and use `Trace_core` instead.

**Comment by joprice** [comment]
I see! Thanks for the quick response. I’ll try that out

**Comment by joprice** [comment]
Should trace-tef depend on trace.core? I probably won't end up having that in a lib vs an executable in then end, but I happened to be running utop against a scratch executable that had both trace and trace-tef, and I had to remove it to get the `_core` change to work.

**Comment by c-cube** [comment]
That's a good point indeed. I'd accept a PR that makes this dependency more precise!

**Comment by joprice** [comment]
Here you go! https://github.com/c-cube/ocaml-trace/pull/3
