### ISSUE TITLE
Using the ppx doesn't seem compatible with the opentelemetry backend

### ISSUE THREAD

**Issue by emjin** [c-cube/ocaml-trace#27]
I'm trying to use the ppx for tracing, since it looks really good! However, I'm having trouble using the opentelemetry backend with trace. Installing `ppx_trace` seems to make `opentelemetry.trace` no longer present.

Here's the process:

This is how I'm currently using opentelemetry. I have a wrapper `with_setup` function that I pass the function I want to trace. This has been working great.
```
let with_setup f =
  let otel_backend =
    Opentelemetry_client_ocurl.create_backend ()
  in
  Opentelemetry_trace.setup_with_otel_backend otel_backend;

  Opentelemetry_client_ocurl.with_setup () @@ fun () ->
  run_with_span "All time" f
```

When I install `ppx_trace`, opam tells me these are the necessary conflict resolution actions.

```
➜  semgrep git:(develop) ✗ opam install ppx_trace
Constructing initial basis...
Number of 0-1 knapsack inequalities = 20710
Constructing conflict graph...
Conflict graph has 3444 + 1337 = 4781 vertices
The following actions will be performed:
  ↘ downgrade opentelemetry                   0.6 to 0.4
  ↗ upgrade   trace                           0.4 to 0.6 [required by ppx_trace]
  ↘ downgrade opentelemetry-client-ocurl      0.6 to 0.4 [uses opentelemetry]
  ↘ downgrade opentelemetry-client-cohttp-lwt 0.6 to 0.4 [uses opentelemetry]
  ∗ install   ppx_trace                       0.6
  ↗ upgrade   trace-tef                       0.4 to 0.6 [uses trace]
===== ∗ 1   ↗ 2   ↘ 3 =====
Do you want to continue? [Y/n] y
```

When I downgrade opentelemetry and opentelemetry-client-ocurl, it seems that I lose `opentelemetry.trace`:
```
➜  semgrep git:(develop) ✗ make core;n
/Library/Developer/CommandLineTools/usr/bin/make minimal-build
dune build _build/install/default/bin/semgrep-core
File "libs/tracing/unix/dune", line 9, characters 3-22:
9 |    opentelemetry.trace
       ^^^^^^^^^^^^^^^^^^^
Error: Library "opentelemetry.trace" not found.
-> required by library "tracing.unix" in _build/default/libs/tracing/unix
-> required by executable Main in src/main/dune:2
-> required by _build/default/src/main/Main.exe
-> required by _build/install/default/bin/semgrep-core
make[1]: *** [minimal-build] Error 1             
make: *** [core] Error 2
```

This means `Opentelemetry_client_ocurl.create_backend` and `Opentelemetry_trace.setup_with_otel_backend` are no longer available.

What's the recommended way to set up opentelemetry and also use the ppx?

**Comment by ELLIOTTCABLE** [comment]
replied on Slack, duplicating here for other visitors: `ocaml-opentelemetry` didn't have a `trace` implementation before v0.5 — that downgrade is sus.

**Comment by ELLIOTTCABLE** [comment]
Yeah, didn't realize that `ocaml-trace` got semver-major bumped when the ppx was added. The dependency constraint will need to be updated in `ocaml-opentelemetry`.

I've been away, not sure what breaking changes @c-cube may have added in v0.6? but I think it should be pretty straightforward to patch. (getting that published to opam may be kinda slow, though; i've very little time at the second)

**Comment by c-cube** [comment]
I could make a release for opentelemetry, it's getting more stable on the 0.6 branch, actually.

@emjin by the way, your `with_setup` function looks good but you need to make sure it's called only once, at the beginning of the program (otherwise it recreates a whole backend, with new threads, ocurl clients, HTTP connections, etc. every time your function is called!!)

**Comment by emjin** [comment]
Fixed in the new opentelemetry release!
